-- Databricks notebook source
CREATE TABLE IF NOT EXISTS silver.personas (
    ID INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOMBRE STRING NOT NULL,
    APELLIDO STRING NOT NULL,
    EDAD INT,
    TELEFONO STRING NOT NULL,
    EMAIL STRING NOT NULL,
    SALARIO DOUBLE,
    FECHA_INGRESO DATE NOT NULL,
    ANIO INT,
    MES INT,
    DIA INT,
    SEGMENTO STRING NOT NULL,
    PERIODO STRING NOT NULL
)
USING DELTA
PARTITIONED BY (PERIODO)
LOCATION 'gs://dmc_datalake_dde_11_javp/produccion/dmc/silver/personas'