
CREATE TABLE MIUSUARIO_TEST2.PERSONA( 
ID STRING, 
NOMBRE STRING, 
TELEFONO STRING, 
CORREO STRING, 
FECHA_INGRESO STRING, 
EDAD INT, 
SALARIO DOUBLE, 
ID_EMPRESA STRING 
)
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '|' 
LINES TERMINATED BY '\n' 
STORED AS TEXTFILE 
LOCATION '/user/miusuario/bd/miusuario_test2/persona'; 

 SELECT * FROM MIUSUARIO_TEST2.PERSONA LIMIT 10; 


 LOAD DATA LOCAL INPATH '/home/julio/persona.data' INTO TABLE MIUSUARIO_TEST2.PERSONA;

 LOAD DATA LOCAL INPATH '/home/julio/persona.data' INTO TABLE MIUSUARIO_TEST2.PERSONA; 


 CREATE EXTERNAL TABLE MIUSUARIO_TEST3.PERSONA ( 
ID STRING, 
NOMBRE STRING, 
TELEFONO STRING, 
CORREO STRING, 
FECHA_INGRESO STRING, 
EDAD INT, 
SALARIO DOUBLE, 
ID_EMPRESA STRING 
) 
STORED AS PARQUET 
LOCATION '/user/miusuario/bd/miusuario_test3/persona_parquet'; 


CREATE TABLE MIUSUARIO_TEST.TRANSACCION( 
ID_PERSONA STRING, 
ID_EMPRESA STRING, 
MONTO DOUBLE 
) 
PARTITIONED BY (FECHA STRING) 
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '|' 
LINES TERMINATED BY '\n' 
STORED AS TEXTFILE 
LOCATION '/user/miusuario/bd/miusuario_test/transaccion';


LOAD DATA LOCAL INPATH '/home/julio/transacciones-2018-01-21.data'  
OVERWRITE INTO TABLE MIUSUARIO_TEST.TRANSACCION  
PARTITION (FECHA='2018-01-21'); 

LOAD DATA LOCAL INPATH '/home/julio/transacciones-2018-01-22.data'  
OVERWRITE INTO TABLE MIUSUARIO_TEST.TRANSACCION  
PARTITION (FECHA='2018-01-22'); 

LOAD DATA LOCAL INPATH '/home/julio/transacciones-2018-01-23.data'  
OVERWRITE INTO TABLE MIUSUARIO_TEST.TRANSACCION  
PARTITION (FECHA='2018-01-23'); 